### ISSUE TITLE
docker upgrade troubles

### ISSUE THREAD

**Issue by kokokenada** [prisma/datamodel-v1.1-feedback#4]
I followed the instructions to upgrade the data mode and ran into a few problems and am still stuck.

* Just editing the docker-compose.yml, and restarting didn't cause the upgrade in the docker environment to work (docker ps showed a 1.2.* version running). docker-compose down, docker-compose rm, followed by a docker-compose up seemed to work (docker ps showed 1.3)
* I also had a prisma in package.json which need to be upgraded (npm install --save prisma@beta) . (Is that normal and should it be added to the steps? - do we even need the npm install -g - might be better to just use local for beta testing)
* But even after all that (and installing prima beta globally)  (prisma --version reports 1.3), when I run prisma deploy it accepts the old data model and complains about new decorators (e.g. @id)

**Comment by kokokenada** [comment]
And forgot to mention probably the most important thing:

When I docker-compose up, I get:

ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.prisma: 'prototype'

When I comment out:
    prototype: true

It runs, but has the (1.2 behavior)

**Comment by mavilein** [comment]
@kokokenada : Can you paste your complete `docker-compose.yml` please?

**Comment by kokokenada** [comment]
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.30-beta
    restart: always
    prototype: true
    ports:
      - '4467:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
            rawAccess: true
  postgres:
    image: postgres:10.5
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:

**Comment by mavilein** [comment]
@kokokenada : The `prototype` flag is not a feature of `docker-compose.yml` but of the `PRISMA_CONFIG` env var. Therefore the config can be fixed like this. I simply moved the `prototype` line:
```yml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.30-beta
    restart: always    
    ports:
      - '4467:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        prototype: true
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
            rawAccess: true
  postgres:
    image: postgres:10.5
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
```

I am closing this issue therefore now. We can reopen again if you are still having trouble 🙏
