### ISSUE TITLE
Postgres: column "uuid" of relation "User" already exists

### ISSUE THREAD

**Issue by diversit** [prisma/datamodel-v1.1-feedback#6]
Deploying a simple User schema to a Postgres db gives no error when deploying, but the Prisma Service log the error:
```
prisma_1    | [Debug] Initializing deployment worker for default$default
prisma_1    | [Debug] Scheduling deployment for project default$default
postgres_1  | 2019-03-27 14:56:15.943 UTC [75] ERROR:  column "uuid" of relation "User" already exists
postgres_1  | 2019-03-27 14:56:15.943 UTC [75] STATEMENT:  ALTER TABLE "default$default"."User" ADD COLUMN "uuid" uuid NOT NULL
prisma_1    | org.postgresql.util.PSQLException: ERROR: column "uuid" of relation "User" already exists
prisma_1    | 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
prisma_1    | Encountered exception while applying migration. Rolling back. org.postgresql.util.PSQLException: ERROR: column "uuid" of relation "User" already exists
prisma_1    | 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
prisma_1    | 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
prisma_1    | 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
prisma_1    | 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
prisma_1    | 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
prisma_1    | 	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144)
prisma_1    | 	at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:38)
prisma_1    | 	at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:21)
prisma_1    | 	at slick.jdbc.Invoker.first(Invoker.scala:30)
prisma_1    | 	at slick.jdbc.Invoker.first$(Invoker.scala:29)
prisma_1    | 	at slick.jdbc.StatementInvoker.first(StatementInvoker.scala:15)
prisma_1    | 	at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:52)
prisma_1    | 	at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:51)
prisma_1    | 	at slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:239)
prisma_1    | 	at scala.collection.Iterator.foreach(Iterator.scala:937)
prisma_1    | 	at scala.collection.Iterator.foreach$(Iterator.scala:937)
prisma_1    | 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
prisma_1    | 	at scala.collection.IterableLike.foreach(IterableLike.scala:70)
prisma_1    | 	at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
prisma_1    | 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
prisma_1    | 	at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:239)
prisma_1    | 	at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:237)
prisma_1    | 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
prisma_1    | 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
prisma_1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
prisma_1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
prisma_1    | 	at java.lang.Thread.run(Thread.java:748)
prisma_1    | [Debug] Applied migration for project default$default
```

Schema:
```
type User @pgTable(name: "users") {
  uuid: UUID! @id
  name: String!
}
```

docker-compose.yaml:
```
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.30-beta
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        prototype: true
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            user: prisma
            password: prisma
            rawAccess: true
            port: 5432
            migrations: true
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
```

prisma version:
```prisma/1.30.0-beta.3 (darwin-x64) node-v11.3.0```
